# Contenu des cinq expériences (EC2 « Maladies et hygiène », 2STE1275)
# Toutes les ressources sont locales, récupérées ou disponibles à l'école : aucun achat.

EXPERIENCES = [
  dict(
    id='exp1', court='Filtre à eau artisanal',
    titre='Expérience 1 : Fabriquer un filtre à eau artisanal et désinfecter l’eau au soleil',
    chapitre='Chapitre 5 (techniques de traitement de l’eau ; fabrication d’un filtre à eau) et chapitre 1 (amibiase, choléra, giardiase : maladies transmises par l’eau souillée)',
    duree='1 h pour la fabrication ; 6 h d’exposition au soleil pour la désinfection',
    objectif=[
      'Fabriquer un filtre à eau avec des matériaux récupérés dans le milieu.',
      'Constater que la filtration clarifie l’eau, mais ne suffit pas à la rendre potable.',
      'Appliquer une méthode de désinfection gratuite : l’exposition au soleil (ou l’ébullition).',
    ],
    materiel=[
      ('Deux bouteilles plastiques transparentes de 1,5 L', 'Bouteilles d’eau ou de boisson vides récupérées'),
      ('Un morceau de pagne usé ou de moustiquaire usée', 'Vieux vêtements, moustiquaire déchirée de la maison'),
      ('Un élastique découpé dans une chambre à air', 'Chambre à air usée (réparateur de vélos ou de motos)'),
      ('Charbon de bois concassé', 'Foyer ou cuisine (restes de charbon)'),
      ('Sable fin, gravier et petits cailloux', 'Cour de l’école, bord de rivière, chantier voisin'),
      ('Eau boueuse', 'Marigot, flaque, caniveau propre après la pluie'),
      ('Calebasse, seau ou bouteille coupée', 'Cuisine de l’école ou de la maison'),
      ('Tôle ondulée', 'Toit ou morceau de tôle usée'),
    ],
    demarche=[
      'Le formateur découpe le fond d’une bouteille avec un couteau de cuisine, puis la retourne : le goulot est en bas.',
      'Fixer le morceau de pagne ou de moustiquaire sur le goulot avec l’élastique de chambre à air : il retiendra les couches.',
      'Laver séparément le charbon, le sable et le gravier jusqu’à ce que l’eau de rinçage soit claire.',
      'Remplir la bouteille en partant du goulot, dans l’ordre du cours : charbon (3 cm), sable fin (4 cm), charbon (3 cm), gravier (4 cm), petits graviers (3 cm).',
      'Poser le filtre sur la calebasse. Verser lentement l’eau boueuse. Jeter la première eau recueillie, qui contient de la poussière de charbon.',
      'Comparer l’eau filtrée avec un témoin : la même eau boueuse, non filtrée, dans une bouteille identique.',
      'Désinfecter : remplir une bouteille transparente propre avec l’eau filtrée claire, la fermer, puis la coucher sur la tôle en plein soleil pendant 6 h (2 jours si le ciel est couvert). À défaut, faire bouillir l’eau au moins 1 minute.',
    ],
    observations=[
      'L’eau recueillie est beaucoup plus claire que l’eau boueuse du témoin.',
      'Les couches supérieures du filtre retiennent la boue et se salissent.',
      'Le débit ralentit à mesure que le filtre se colmate.',
    ],
    interpretation=[
      'Le gravier, le sable et le charbon retiennent les particules en suspension : c’est la filtration.',
      'Une eau claire peut encore contenir des microbes invisibles à l’œil nu. La filtration doit donc être suivie d’une désinfection.',
      'Les rayons du soleil (ultraviolets) et la chaleur détruisent la plupart des germes : c’est le principe de la désinfection solaire.',
      'Boire une eau traitée prévient l’amibiase, le choléra, la giardiase et la fièvre typhoïde.',
    ],
    securite=[
      'La découpe des bouteilles est faite par le formateur.',
      'Ne jamais boire l’eau seulement filtrée.',
      'La désinfection solaire ne fonctionne qu’avec une eau claire et une bouteille transparente de 2 L au plus.',
      'Se laver les mains au savon après avoir manipulé l’eau du marigot.',
    ],
    prolongement=[
      'Comparer trois filtres : sable seul, charbon seul, filtre complet.',
      'Réaliser une affiche « De l’eau boueuse à l’eau potable » pour le coin santé de l’école.',
    ],
    mm=dict(
      objectif=['Fabriquer un filtre avec du matériel récupéré', 'Clarifier une eau boueuse', 'Désinfecter l’eau au soleil'],
      materiel=['2 bouteilles plastiques de 1,5 L', 'Pagne ou moustiquaire usé(e)', 'Élastique de chambre à air', 'Charbon de bois, sable, gravier', 'Eau boueuse du marigot', 'Calebasse, tôle du toit'],
      demarche=['1. Couper et retourner la bouteille', '2. Fixer le tissu au goulot', '3. Laver charbon, sable et gravier', '4. Superposer les couches', '5. Verser l’eau boueuse', '6. Comparer avec un témoin', '7. 6 h au soleil ou ébullition'],
      observations=['Eau filtrée plus claire', 'Couches du haut salies', 'Débit qui ralentit'],
      conclusion=['Filtration : retient les particules', 'Eau claire ≠ eau potable', 'Désinfection : soleil ou ébullition', 'Prévient choléra et amibiase'],
      securite=['Découpe par le formateur', 'Ne pas boire l’eau seulement filtrée', 'Se laver les mains au savon'],
      cours=['Chapitre 5 : traitement de l’eau', 'Chapitre 1 : maladies hydriques'],
    ),
  ),
  dict(
    id='exp2', court='Goudron du tabac',
    titre='Expérience 2 : Mettre en évidence le goudron du tabac avec une « machine à fumer »',
    chapitre='Chapitre 4 (effets de la consommation du tabac sur l’organisme) ; travail pratique prévu par le support : « expérience de la mise en évidence du goudron du tabac »',
    duree='30 min',
    objectif=[
      'Montrer que la fumée de cigarette contient des goudrons qui se déposent dans les voies respiratoires.',
      'Relier ce dépôt aux méfaits du tabac cités dans le cours : toux, souffle court, cancer des poumons.',
    ],
    materiel=[
      ('Une bouteille plastique souple de 1,5 L avec son bouchon', 'Bouteille vide récupérée'),
      ('Un tampon de coton ou un morceau de tissu blanc', 'Trousse de secours de l’école ou vieux tee-shirt blanc'),
      ('Une cigarette', 'Cigarette récupérée auprès d’un adulte fumeur volontaire ou confisquée (aucun achat par les élèves)'),
      ('Un clou et une bougie ou un foyer', 'Atelier et cuisine de l’école'),
      ('Des allumettes', 'Cuisine'),
      ('Un peu d’eau et une feuille de papier blanc', 'Salle de classe'),
      ('Un seau d’eau', 'Pour éteindre et jeter le mégot'),
    ],
    demarche=[
      'Chauffer la pointe du clou et percer le bouchon d’un trou du diamètre de la cigarette (formateur).',
      'Placer le tampon de coton blanc dans le goulot, juste sous le bouchon : il représente les poumons.',
      'Verser 2 à 3 cm d’eau au fond de la bouteille.',
      'Enfoncer la cigarette dans le trou du bouchon (filtre vers l’intérieur), puis revisser le bouchon.',
      'En plein air, le formateur presse la bouteille, allume la cigarette, puis relâche lentement : la bouteille « aspire » la fumée. Répéter une dizaine de fois, jusqu’à ce que la cigarette soit consumée.',
      'Éteindre le mégot dans le seau d’eau. Retirer le coton et le comparer à un coton neuf (témoin). Le frotter sur le papier blanc et sentir l’eau.',
    ],
    observations=[
      'Le coton, blanc au départ, devient jaune puis brun ; il est collant.',
      'Le coton frotté laisse une trace brune sur le papier.',
      'L’eau jaunit et dégage une odeur âcre ; les parois de la bouteille se ternissent.',
    ],
    interpretation=[
      'La fumée transporte des goudrons et de la nicotine qui se déposent sur le coton, comme ils se déposent dans les bronches et les poumons du fumeur.',
      'Ces dépôts expliquent la toux, le souffle court, la mauvaise haleine et le cancer des poumons (effets cités au chapitre 4).',
      'Les personnes qui respirent la fumée des autres (fumeurs passifs) sont également exposées.',
    ],
    securite=[
      'L’expérience est réalisée uniquement par le formateur, en plein air.',
      'Les élèves se tiennent à au moins 3 m, dos au vent, et n’inhalent jamais la fumée.',
      'Ne jamais faire fumer un élève.',
      'Garder le seau d’eau à portée de main ; éteindre le mégot dans l’eau.',
    ],
    prolongement=[
      'Coller le coton noirci sur une affiche : « Le tabac noircit tes poumons ».',
      'Calculer le nombre de cigarettes fumées en un an par une personne qui fume un paquet par jour (20 × 365 = 7 300).',
    ],
    mm=dict(
      objectif=['Montrer le goudron de la fumée', 'Relier au cancer et à la toux'],
      materiel=['Bouteille souple et bouchon', 'Coton ou tissu blanc', 'Cigarette récupérée (sans achat)', 'Clou chauffé, allumettes', 'Eau, papier blanc, seau'],
      demarche=['1. Percer le bouchon', '2. Coton dans le goulot', '3. Un peu d’eau au fond', '4. Cigarette dans le bouchon', '5. Presser, allumer, relâcher', '6. Comparer au coton témoin'],
      observations=['Coton jaune puis brun', 'Trace brune sur le papier', 'Eau jaunie, odeur âcre'],
      conclusion=['Goudrons déposés dans les poumons', 'Toux, souffle court, cancer', 'Danger du tabagisme passif'],
      securite=['Formateur seul, en plein air', 'Élèves à 3 m, dos au vent', 'Mégot éteint dans l’eau'],
      cours=['Chapitre 4 : tabac et organisme', 'TP prévu par le support'],
    ),
  ),
  dict(
    id='exp3', court='Microbes des mains',
    titre='Expérience 3 : Rendre visibles les microbes des mains sales',
    chapitre='Chapitre 1 (maladies microbiennes : définition du microbe, moyens de prévention par le lavage des mains) ; chapitre 3 (prévention de la fièvre Ebola par le lavage des mains à l’eau et au savon)',
    duree='20 min de préparation ; 5 à 7 jours d’observation',
    objectif=[
      'Montrer que les mains transportent des microbes invisibles à l’œil nu.',
      'Comparer des mains non lavées et des mains lavées à l’eau et au savon.',
      'Justifier le lavage des mains comme moyen de prévention du choléra, de l’amibiase et de la fièvre Ebola.',
    ],
    materiel=[
      ('Trois tranches d’un même aliment cuit (igname, patate douce, pâte de maïs, pain rassis)', 'Restes du repas de la cantine ou de la maison'),
      ('Trois sachets plastiques transparents propres et du fil', 'Sachets de sucre ou de glace récupérés'),
      ('Une cuillère et un couteau ébouillantés', 'Cuisine'),
      ('Du savon et de l’eau propre', 'Savon local (savon noir, « koto ») du lave-mains de l’école'),
      ('Un morceau de charbon ou un stylo pour étiqueter', 'Salle de classe'),
    ],
    demarche=[
      'Ébouillanter la cuillère et le couteau. Couper trois tranches identiques dans l’aliment refroidi.',
      'Sachet A (témoin) : glisser la tranche dans le sachet avec la cuillère, sans la toucher.',
      'Sachet B : un élève qui vient de jouer dans la cour frotte la tranche avec ses mains non lavées.',
      'Sachet C : le même élève se lave les mains 30 secondes à l’eau et au savon (paumes, dos, entre les doigts, ongles), les sèche à l’air, puis touche la tranche de la même façon.',
      'Humecter chaque tranche de quelques gouttes d’eau bouillie, fermer les sachets avec le fil, les étiqueter A, B et C et les ranger dans une armoire sombre.',
      'Observer chaque jour pendant 5 à 7 jours, à travers le sachet et sans l’ouvrir. Noter et dessiner les taches (nombre, couleur, taille) dans un tableau.',
    ],
    observations=[
      'Tranche B (mains non lavées) : nombreuses taches vertes, noires ou blanches qui s’étendent vite.',
      'Tranche C (mains lavées) : peu de taches, qui apparaissent plus tard.',
      'Tranche A (témoin) : pas ou très peu de taches.',
    ],
    interpretation=[
      'Les mains transportent des microbes invisibles à l’œil nu. Sur un aliment humide, ils se multiplient et forment des taches visibles (colonies de moisissures et de bactéries).',
      'Le lavage à l’eau et au savon élimine la plus grande partie de ces microbes.',
      'Se laver les mains avant de manger et après les toilettes prévient le choléra, l’amibiase, la giardiase et la fièvre Ebola (moyens de prévention du cours).',
    ],
    securite=[
      'Ne jamais ouvrir les sachets après l’incubation : les moisissures libèrent des spores.',
      'Ne pas goûter les aliments de l’expérience.',
      'Jeter les sachets fermés dans la fosse à ordures ou les enfouir ; ne pas les brûler.',
      'Se laver les mains à la fin de chaque observation.',
    ],
    prolongement=[
      'Construire un lave-mains à pédale (« tippy-tap ») avec un bidon de 5 L, deux bâtons et une ficelle.',
      'Composer une chanson de 30 secondes pour rythmer le lavage des mains.',
    ],
    mm=dict(
      objectif=['Voir les microbes invisibles', 'Comparer mains sales et lavées', 'Justifier le lavage des mains'],
      materiel=['3 tranches d’igname ou de pâte', '3 sachets transparents récupérés', 'Cuillère et couteau ébouillantés', 'Savon local et eau'],
      demarche=['1. Couper 3 tranches', '2. A : témoin, sans contact', '3. B : mains non lavées', '4. C : mains lavées au savon', '5. Fermer, étiqueter, ranger', '6. Observer 5 à 7 jours'],
      observations=['B : nombreuses taches', 'C : peu de taches', 'A : pas de taches'],
      conclusion=['Les mains portent des microbes', 'Le savon en élimine la plupart', 'Prévient choléra, amibiase, Ebola'],
      securite=['Ne jamais ouvrir les sachets', 'Ne pas goûter, ne pas brûler', 'Se laver les mains'],
      cours=['Chapitre 1 : maladies microbiennes', 'Chapitre 3 : prévention d’Ebola'],
    ),
  ),
  dict(
    id='exp4', court='Larves de moustiques',
    titre='Expérience 4 : Observer le développement des larves de moustiques et détruire leurs gîtes',
    chapitre='Chapitre 1 (paludisme : cycle évolutif, rôle de l’anophèle, destruction des flaques et des boîtes contenant de l’eau, couverture des récipients)',
    duree='1 h de sortie ; 7 jours d’observation au plus',
    objectif=[
      'Repérer les gîtes larvaires autour de l’école.',
      'Observer les stades du moustique : larve, nymphe, adulte.',
      'Comprendre pourquoi la suppression de l’eau stagnante et la moustiquaire protègent du paludisme.',
    ],
    materiel=[
      ('Eau stagnante contenant des larves', 'Vieux pneu, boîte de conserve, pot cassé, jarre non couverte'),
      ('Une bouteille plastique transparente coupée ou un bocal', 'Récupération'),
      ('Un morceau de moustiquaire usée et un élastique de chambre à air', 'Moustiquaire déchirée, chambre à air usée'),
      ('Une boîte de tomate vide pour prélever', 'Cuisine'),
      ('Un cahier et un crayon', 'Salle de classe'),
    ],
    demarche=[
      'Faire le tour de l’école et du quartier voisin. Recenser les gîtes dans un tableau (lieu, type de récipient, larves : oui ou non).',
      'Avec la boîte de tomate, prélever de l’eau contenant des larves et la verser dans la bouteille coupée.',
      'Couvrir immédiatement avec la moustiquaire bien tendue, fixée par l’élastique : aucun moustique ne doit pouvoir s’échapper.',
      'Placer le récipient à l’ombre, dans la classe. Observer matin et soir. Taper doucement sur la paroi : les larves plongent, puis remontent respirer à la surface.',
      'Distinguer les larves d’anophèle (couchées à l’horizontale sous la surface) de celles du culex (suspendues en oblique par un siphon), puis repérer les nymphes en forme de virgule.',
      'Noter chaque jour le stade observé et dessiner les larves et les nymphes.',
      'Au 7e jour au plus tard, verser l’eau sur un sol sec en plein soleil, puis laver le récipient. Vider, renverser ou couvrir tous les gîtes recensés.',
    ],
    observations=[
      'Les larves se tortillent et remontent régulièrement respirer à la surface.',
      'Après quelques jours, apparaissent des nymphes en forme de virgule.',
      'Des moustiques adultes peuvent émerger sous la moustiquaire vers le 7e jour.',
    ],
    interpretation=[
      'Il suffit d’un peu d’eau stagnante pour que le moustique se reproduise.',
      'Supprimer l’eau stagnante interrompt le cycle : pas d’eau, pas de larves, pas de moustiques.',
      'La femelle de l’anophèle transmet le plasmodium du paludisme. La moustiquaire empêche sa piqûre, comme elle a empêché les adultes de sortir du récipient.',
    ],
    securite=[
      'Le récipient reste toujours couvert.',
      'Ne pas conserver les larves plus de 7 jours.',
      'Ne pas prélever dans des eaux profondes ou dangereuses.',
      'Se laver les mains après chaque manipulation.',
    ],
    prolongement=[
      'Élaborer la planche du cycle évolutif du paludisme (travail pratique prévu par le support).',
      'Dessiner la carte des gîtes de l’école et organiser une journée de salubrité.',
    ],
    mm=dict(
      objectif=['Repérer les gîtes larvaires', 'Observer larve, nymphe, adulte', 'Justifier la prévention du paludisme'],
      materiel=['Eau stagnante avec larves', 'Bouteille coupée ou bocal', 'Moustiquaire usée et élastique', 'Boîte de tomate vide'],
      demarche=['1. Recenser les gîtes', '2. Prélever larves et eau', '3. Couvrir avec la moustiquaire', '4. Observer matin et soir', '5. Anophèle ou culex ?', '6. Noter et dessiner', '7. Jour 7 : vider et détruire'],
      observations=['Larves qui respirent en surface', 'Nymphes en virgule', 'Adultes vers le jour 7'],
      conclusion=['Peu d’eau suffit', 'Pas d’eau, pas de moustiques', 'Moustiquaire = barrière'],
      securite=['Toujours couvrir', '7 jours au plus', 'Se laver les mains'],
      cours=['Chapitre 1 : paludisme', 'Cycle du plasmodium'],
    ),
  ),
  dict(
    id='exp5', court='Déchets biodégradables',
    titre='Expérience 5 : Biodégradable ou non ? Enfouir et comparer les déchets',
    chapitre='Chapitre 6 (éléments polluants ; enfouir les déchets organiques biodégradables et recycler les non biodégradables) et chapitre 5 (aménagement des dépotoirs)',
    duree='1 h de mise en place ; 3 à 4 semaines d’attente',
    objectif=[
      'Distinguer les déchets biodégradables des déchets non biodégradables.',
      'Comprendre le rôle des décomposeurs du sol.',
      'Choisir le bon traitement pour chaque déchet : compostage, collecte ou recyclage.',
    ],
    materiel=[
      ('Épluchures (manioc, banane, orange) et feuilles mortes', 'Cuisine, cour de l’école'),
      ('Papier, sachet plastique d’eau, morceau de boîte de conserve', 'Poubelles de l’école'),
      ('Une houe (daba) ou un coupe-coupe', 'Matériel du jardin scolaire'),
      ('Cinq piquets de bois ou de bambou et des étiquettes en carton', 'Branches, cartons récupérés'),
      ('Un arrosoir ou une boîte percée', 'Jardin scolaire'),
      ('Variante : cinq bouteilles coupées remplies de terre humide', 'Récupération'),
    ],
    demarche=[
      'Collecter les déchets, en protégeant ses mains avec des sachets plastiques retournés.',
      'Dans le jardin scolaire, creuser cinq trous de 15 à 20 cm de profondeur, espacés de 50 cm.',
      'Déposer un type de déchet par trou et noter son état initial (dessin, taille, couleur).',
      'Reboucher chaque trou, planter un piquet étiqueté, puis arroser légèrement chaque semaine pour garder le sol humide.',
      'Variante visible : placer chaque déchet contre la paroi d’une bouteille coupée remplie de terre, afin de suivre son évolution sans creuser.',
      'Après 3 à 4 semaines, déterrer, observer et remplir un tableau comparatif (transformé ou intact, couleur, odeur, petites bêtes présentes).',
      'Remettre les déchets organiques dans une fosse à compost. Collecter le plastique et le métal pour les recycler.',
    ],
    observations=[
      'Les épluchures et les feuilles sont presque décomposées ; des vers de terre ou des termites sont présents.',
      'Le papier est ramolli et en partie décomposé.',
      'Le sachet plastique est intact ; le métal est seulement rouillé.',
    ],
    interpretation=[
      'Les décomposeurs du sol (bactéries, champignons, vers) transforment les déchets organiques en humus : ce sont des déchets biodégradables, utilisables en compost.',
      'Le plastique et le métal ne sont pas décomposés : ils restent des dizaines, voire des centaines d’années dans le sol.',
      'Les sachets plastiques bouchent les caniveaux et retiennent l’eau, qui devient un gîte à moustiques (lien avec l’expérience 4). Brûlés, ils libèrent des gaz polluants.',
      'Il faut donc enfouir ou composter les déchets organiques, et recycler les déchets non biodégradables (cours, chapitre 6).',
    ],
    securite=[
      'Ne pas utiliser de verre, de piles ni de déchets médicaux.',
      'Protéger ses mains et se laver les mains au savon à la fin de chaque séance.',
      'Creuser loin des latrines et des points d’eau.',
    ],
    prolongement=[
      'Créer une fosse compostière pour le jardin scolaire.',
      'Organiser un atelier de recyclage des sachets plastiques (tressage de sacs, pavés plastique-sable réalisés par le formateur).',
    ],
    mm=dict(
      objectif=['Biodégradable ou non ?', 'Rôle des décomposeurs', 'Choisir compost ou recyclage'],
      materiel=['Épluchures, feuilles, papier', 'Sachet plastique, boîte de conserve', 'Houe (daba), piquets, cartons', 'Arrosoir ou boîte percée'],
      demarche=['1. Collecter les déchets', '2. Creuser 5 trous de 15 à 20 cm', '3. Un déchet par trou', '4. Reboucher, étiqueter, arroser', '5. Variante en bouteilles', '6. Déterrer après 3 à 4 semaines', '7. Composter ou recycler'],
      observations=['Épluchures et feuilles décomposées', 'Papier ramolli', 'Plastique intact, métal rouillé'],
      conclusion=['Décomposeurs → humus', 'Le plastique persiste', 'Enfouir l’organique, recycler le reste'],
      securite=['Ni verre, ni piles, ni déchets médicaux', 'Mains protégées puis lavées', 'Loin des latrines'],
      cours=['Chapitre 6 : environnement', 'Chapitre 5 : dépotoirs'],
    ),
  ),
]

BRANCHES = [  # (clé, libellé, côté, couleur)
  ('objectif', 'Objectifs', 'right', '#1F77B4'),
  ('materiel', 'Matériel local', 'right', '#2CA02C'),
  ('demarche', 'Démarche', 'right', '#D62728'),
  ('observations', 'Observations', 'left', '#9467BD'),
  ('conclusion', 'Interprétation', 'left', '#8C564B'),
  ('securite', 'Sécurité', 'left', '#E377C2'),
  ('cours', 'Lien avec le cours', 'left', '#FF7F0E'),
]

MORINGA = [dict(
    id='exp6', court='Eau clarifiée au moringa',
    titre='Expérience 6 : Clarifier et purifier une eau boueuse avec les graines de moringa',
    chapitre='Chapitre 5 (techniques de traitement de l’eau : sédimentation, filtration, désinfection) et chapitre 1 (amibiase, choléra, giardiase, fièvre typhoïde : maladies transmises par l’eau souillée)',
    duree='20 min de préparation ; 1 à 2 h de décantation ; 6 h au soleil pour la désinfection',
    objectif=[
      'Utiliser les graines de moringa, une ressource végétale locale, pour clarifier une eau boueuse.',
      'Comprendre les étapes du traitement : coagulation, floculation, décantation, filtration.',
      'Montrer qu’une eau clarifiée doit encore être désinfectée avant d’être bue.',
    ],
    materiel=[
      ('Gousses sèches de moringa (*Moringa oleifera*) : 6 graines pour l’expérience', 'Arbre de moringa de la cour, du quartier ou du jardin familial'),
      ('Deux pierres propres, ou un mortier et un pilon', 'Cour de l’école, cuisine'),
      ('Un petit flacon avec bouchon et un peu d’eau propre', 'Petite bouteille récupérée'),
      ('Trois bouteilles transparentes de 1,5 L avec bouchon', 'Bouteilles d’eau ou de boisson vides'),
      ('Eau boueuse', 'Marigot, rivière, flaque après la pluie'),
      ('Un morceau de pagne propre, à tissage fin', 'Vieux pagne lavé'),
      ('Une bouteille transparente propre et une tôle ondulée', 'Récupération ; toit ou tôle usée'),
    ],
    demarche=[
      'Récolter des gousses mûres et sèches (brunes). Extraire les graines et retirer leur enveloppe ailée pour obtenir l’amande blanche.',
      'Écraser finement 3 amandes entre deux pierres propres ou au mortier, jusqu’à obtenir une poudre blanche. Préparer ainsi deux doses de 3 amandes (une dose pour 1,5 L d’eau très boueuse ; 2 amandes suffisent si l’eau est peu trouble).',
      'Mélanger chaque dose de poudre avec un peu d’eau propre dans le petit flacon fermé et agiter 1 minute : on obtient une pâte laiteuse.',
      'Remplir les trois bouteilles avec la même eau boueuse, bien mélangée. Bouteille A : témoin, sans rien. Bouteilles B et C : verser une dose de pâte dans chacune.',
      'Fermer les bouteilles B et C, les agiter vigoureusement 1 minute (mélange rapide), puis les retourner lentement 15 à 20 fois pendant 5 minutes (mélange lent) : de petits flocons se forment.',
      'Poser les trois bouteilles côte à côte, sans les bouger, pendant 1 à 2 h. Comparer leur aspect toutes les 15 minutes.',
      'Verser doucement l’eau claire du haut de la bouteille C à travers le pagne plié en quatre, dans la bouteille propre, sans remuer le dépôt du fond.',
      'Désinfecter l’eau obtenue : la coucher sur la tôle en plein soleil pendant 6 h, ou la faire bouillir au moins 1 minute. La consommer dans les 24 h.',
    ],
    observations=[
      'Quelques minutes après le mélange, de petits flocons apparaissent dans les bouteilles B et C.',
      'Après 1 à 2 h, les bouteilles B et C sont claires, avec un dépôt de boue au fond ; la bouteille A reste trouble.',
      'L’eau de la bouteille C, passée au pagne, est limpide.',
    ],
    interpretation=[
      'Les graines de moringa contiennent des protéines qui attirent les fines particules d’argile en suspension : les particules s’agglomèrent (coagulation), forment des flocons (floculation) qui, plus lourds, tombent au fond (décantation).',
      'Ce traitement élimine la plus grande partie de la boue et une partie des bactéries fixées aux particules, mais pas tous les microbes.',
      'La désinfection au soleil ou par ébullition reste donc indispensable : on retrouve les trois étapes du cours (sédimentation, filtration, désinfection).',
      'Le moringa remplace gratuitement les produits chimiques (sulfate d’aluminium) utilisés dans les stations de traitement de l’eau.',
    ],
    securite=[
      'Ne jamais boire l’eau seulement clarifiée : toujours la désinfecter.',
      'Utiliser des graines saines, sèches et non moisies ; préparer la pâte le jour même.',
      'Ne pas dépasser la dose : trop de poudre trouble de nouveau l’eau et favorise le retour des microbes.',
      'Consommer l’eau traitée dans les 24 h et la conserver dans un récipient propre et couvert.',
      'Se laver les mains au savon après avoir manipulé l’eau du marigot.',
    ],
    prolongement=[
      'Tester plusieurs doses (1, 2, 3 et 4 amandes par litre) pour trouver la dose la plus efficace pour l’eau du marigot local.',
      'Combiner le moringa avec le filtre à sable et à charbon de l’expérience 1.',
      'Planter des moringa dans le jardin scolaire : leurs feuilles sont aussi riches en éléments nutritifs.',
    ],
    mm=dict(
      objectif=['Clarifier l’eau avec une plante locale', 'Coagulation, floculation, décantation', 'Désinfecter avant de boire'],
      materiel=['Graines sèches de moringa', 'Pierres ou mortier et pilon', '3 bouteilles de 1,5 L', 'Eau boueuse du marigot', 'Pagne propre, tôle du toit'],
      demarche=['1. Décortiquer les graines', '2. Écraser 3 amandes en poudre', '3. Pâte avec un peu d’eau', '4. A témoin ; B et C + moringa', '5. Agiter vite puis lentement', '6. Reposer 1 à 2 h', '7. Filtrer au pagne', '8. 6 h au soleil ou ébullition'],
      observations=['Flocons en quelques minutes', 'B et C claires, dépôt au fond', 'A reste trouble'],
      conclusion=['Les protéines agglomèrent la boue', 'Flocons lourds → dépôt', 'Moins de microbes, pas zéro', 'Remplace le sulfate d’aluminium'],
      securite=['Toujours désinfecter', 'Graines saines, dose respectée', 'Boire dans les 24 h', 'Se laver les mains au savon'],
      cours=['Chapitre 5 : traitement de l’eau', 'Chapitre 1 : maladies hydriques'],
    ),
)]
